name       : pspp
version    : 1.4.0
release    : 8
source     :
    - https://ftp.gnu.org/gnu/pspp/pspp-1.4.0.tar.gz : 631073120c69ed0b6c0b636c2a36486bc616db1b71210dc8e2a358674bcb663f
license    : GPL-3.0-or-later
component  : office.maths
summary    : Statistical analysis program
description: |
    A free and open source alternative to the proprietary (and expensive) statistical analysis software, SPSS, by IBM. Published by the Free Software Foundation.
builddeps  :
    - pkgconfig(gsl)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(spread-sheet-widget)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
