name       : pspp
version    : 1.2.0
release    : 7
source     :
    - https://ftp.gnu.org/gnu/pspp/pspp-1.2.0.tar.gz : a50e437974cff8d57f41ba87026509c9c383474e52717944ea6565e6ff11f71e
license    : GPL-3.0-or-later
component  : office.maths
summary    : Statistical analysis program
description: |
    A free and open source alternative to the proprietary (and expensive) statistical analysis software, SPSS, by IBM. Published by the Free Software Foundation.
builddeps  :
    - pkgconfig(cairo-egl)
    - pkgconfig(gsl)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(spread-sheet-widget)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
