name       : pspp
version    : 1.4.1
release    : 10
source     :
    - https://ftp.gnu.org/gnu/pspp/pspp-1.4.1.tar.gz : 56b551184f86f2664a1ae8e1558788c40b30cd4fe876dafa4f609d63a0561953
license    : GPL-3.0-or-later
component  : office.maths
summary    : Statistical analysis program
description: |
    A free and open source alternative to the proprietary (and expensive) statistical analysis software, SPSS, by IBM. Published by the Free Software Foundation.
builddeps  :
    - pkgconfig(gsl)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(spread-sheet-widget)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
