name       : pspp
version    : 1.0.1
release    : 3
source     :
    - http://www.nic.funet.fi/pub/gnu/ftp.gnu.org/pub/gnu/pspp/pspp-1.0.1.tar.gz : ba281a2e5d7d40e22f36f07f434a4fbc5be49c6d15740b121c299d024aae1ae5
license    : GPL-3.0
component  : office.maths
summary    : Statistical analysis program
description: |
    A free and open source alternative to the proprietary (and expensive) statistical analysis software, SPSS, by IBM. Published by the Free Software Foundation.
builddeps  :
    - pkgconfig(cairo-egl)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(gsl)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
