name       : pspp
version    : 0.10.2
release    : 1
source     :
    - http://mirror.nexcess.net/gnu/pspp/pspp-0.10.2.tar.gz : f77cacae6948689a60f1a5808a5d2e183c1cd0847c7fc6142646c63814c0daa9
license    : GPL-3.0
component  : office.maths
summary    : Statistical analysis program
description: |
    A free and open source alternative to the proprietary (and expensive) statistical analysis software, SPSS, by IBM. Published by the Free Software Foundation.
builddeps  :
    - pkgconfig(cairo-egl)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(gsl)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
